apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJjblZ6ZEhaaGJIWmxPbWRvY0Y5SVVubE9TalZEVjFKa2IxRllOakJYWWt0eE5uTm1la2xEU2treWVXZ3pkazA0Y1ZnPSIKICAgIH0KICB9LAogICJjdXJyZW50Q29udGV4dCI6ICJwb2RtYW4iLAogICJjbGlQbHVnaW5zRXh0cmFEaXJzIjogWyIvb3B0L2hvbWVicmV3L2xpYi9kb2NrZXIvY2xpLXBsdWdpbnMiXQp9Cg==
type: kubernetes.io/dockerconfigjson
